PRODUCT_COPY_FILES := \
    prebuilded_gapps_rpi3/framework/com.google.android.pano.v1.jar:system/framework/com.google.android.pano.v1.jar \
    prebuilded_gapps_rpi3/framework/com.google.widevine.software.drm.jar:system/framework/com.google.widevine.software.drm.jar \
    prebuilded_gapps_rpi3/etc/sysconfig/google_build.xml:system/etc/sysconfig/google_build.xml \
    prebuilded_gapps_rpi3/etc/sysconfig/google.xml:system/etc/sysconfig/google.xml \
    prebuilded_gapps_rpi3/etc/permissions/com.google.android.pano.v1.xml:system/etc/permissions/com.google.android.pano.v1.xml \
    prebuilded_gapps_rpi3/etc/permissions/com.google.android.tv.installed.xml:system/etc/permissions/com.google.android.tv.installed.xml \
    prebuilded_gapps_rpi3/etc/permissions/com.google.widevine.software.drm.xml:system/etc/permissions/com.google.widevine.software.drm.xml \
    prebuilded_gapps_rpi3/app/SecondScreenSetupAuthBridge/SecondScreenSetupAuthBridge.apk:system/app/SecondScreenSetupAuthBridge/SecondScreenSetupAuthBridge.apk \
    prebuilded_gapps_rpi3/app/WebViewGoogle/WebViewGoogle.apk:system/app/WebViewGoogle/WebViewGoogle.apk: \
    prebuilded_gapps_rpi3/app/GoogleContactsSyncAdapter/GoogleContactsSyncAdapter.apk:system/app/GoogleContactsSyncAdapter/GoogleContactsSyncAdapter.apk \
    prebuilded_gapps_rpi3/app/VideosPano/VideosPano.apk:system/app/VideosPano/VideosPano.apk \
    prebuilded_gapps_rpi3/app/PlayGames/PlayGames.apk:system/app/PlayGames/PlayGames.apk \
    prebuilded_gapps_rpi3/app/Backdrop/Backdrop.apk:system/app/Backdrop/Backdrop.apk \
    prebuilded_gapps_rpi3/app/YouTubeLeanback/YouTubeLeanback.apk:system/app/YouTubeLeanback/YouTubeLeanback.apk \
    prebuilded_gapps_rpi3/app/NoTouchAuthDelegate/NoTouchAuthDelegate.apk:system/app/NoTouchAuthDelegate/NoTouchAuthDelegate.apk \
    prebuilded_gapps_rpi3/app/Music2Pano/Music2Pano.apk:system/app/Music2Pano/Music2Pano.apk \
    prebuilded_gapps_rpi3/app/AtvWidget/AtvWidget.apk:system/app/AtvWidget/AtvWidget.apk \
    prebuilded_gapps_rpi3/app/BugReportSender/BugReportSender.apk:system/app/BugReportSender/BugReportSender.apk \
    prebuilded_gapps_rpi3/app/SecondScreenSetup/SecondScreenSetup.apk:system/app/SecondScreenSetup/SecondScreenSetup.apk \
    prebuilded_gapps_rpi3/app/LandscapeWallpaper/LandscapeWallpaper.apk:system/app/LandscapeWallpaper/LandscapeWallpaper.apk \
    prebuilded_gapps_rpi3/app/talkback/talkback.apk:system/app/talkback/talkback.apk \
    prebuilded_gapps_rpi3/app/GoogleExtShared/GoogleExtShared.apk:system/app/GoogleExtShared/GoogleExtShared.apk \
    prebuilded_gapps_rpi3/app/LeanbackIme/LeanbackIme.apk:system/app/LeanbackIme/LeanbackIme.apk \
    prebuilded_gapps_rpi3/priv-app/PrebuiltGmsCorePano/PrebuiltGmsCorePano.apk:system/priv-app/PrebuiltGmsCorePano/PrebuiltGmsCorePano.apk \
    prebuilded_gapps_rpi3/priv-app/Overscan/Overscan.apk:system/priv-app/Overscan/Overscan.apk \
    prebuilded_gapps_rpi3/priv-app/RecommendationsService/RecommendationsService.apk:system/priv-app/RecommendationsService/RecommendationsService.apk \
    prebuilded_gapps_rpi3/priv-app/RemoteControlService/RemoteControlService.apk:system/priv-app/RemoteControlService/RemoteControlService.apk \
    prebuilded_gapps_rpi3/priv-app/GoogleBackupTransport/GoogleBackupTransport.apk:system/priv-app/GoogleBackupTransport/GoogleBackupTransport.apk \
    prebuilded_gapps_rpi3/priv-app/TV/TV.apk:system/priv-app/TV/TV.apk \
    prebuilded_gapps_rpi3/priv-app/GooglePackageInstaller/GooglePackageInstaller.apk:system/priv-app/GooglePackageInstaller/GooglePackageInstaller.apk \
    prebuilded_gapps_rpi3/priv-app/AtvRemoteService/AtvRemoteService.apk:system/priv-app/AtvRemoteService/AtvRemoteService.apk \
    prebuilded_gapps_rpi3/priv-app/Tubesky/Tubesky.apk:system/priv-app/Tubesky/Tubesky.apk \
    prebuilded_gapps_rpi3/priv-app/AndroidMediaShell/AndroidMediaShell.apk:system/priv-app/AndroidMediaShell/AndroidMediaShell.apk \
    prebuilded_gapps_rpi3/priv-app/GlobalKeyInterceptor/GlobalKeyInterceptor.apk:system/priv-app/GlobalKeyInterceptor/GlobalKeyInterceptor.apk \
    prebuilded_gapps_rpi3/priv-app/GoogleExtServices/GoogleExtServices.apk:system/priv-app/GoogleExtServices/GoogleExtServices.apk \
    prebuilded_gapps_rpi3/priv-app/Katniss/Katniss.apk:system/priv-app/Katniss/Katniss.apk \
    prebuilded_gapps_rpi3/priv-app/LeanbackLauncher/LeanbackLauncher.apk:system/priv-app/LeanbackLauncher/LeanbackLauncher.apk \
    prebuilded_gapps_rpi3/priv-app/ConfigUpdater/ConfigUpdater.apk:system/priv-app/ConfigUpdater/ConfigUpdater.apk \
    prebuilded_gapps_rpi3/priv-app/GoogleServicesFramework/GoogleServicesFramework.apk:system/priv-app/GoogleServicesFramework/GoogleServicesFramework.apk \
    prebuilded_gapps_rpi3/priv-app/CanvasPackageInstaller/CanvasPackageInstaller.apk:system/priv-app/CanvasPackageInstaller/CanvasPackageInstaller.apk
